### ISSUE TITLE
Fails in BRIR mode with MLS sequence

### ISSUE THREAD

**Issue by jdemuynke** [NYU-ImmersiveAudio/ScanIR#1]
The calculation of BRIRs from the raw recorded data fails when using MLS sequence in BRIR mode. Please find below the error message I'm getting in Matlab Command Window.

ScanIR is a measurement tool developed by NYU Steinhardt`s Music and Audio Research Lab.
Psychtoolbox -> detected!
Arduino Support Package -> not detected. Rotating motor feature not available. More info.
Signal Processing Toolbox -> detected
SOFA Matlab/Octave API version 1.0.2. Copyright 2013 Acoustics Research Institute (piotr@majdak.com).
This API implements SOFA version 1.0.
Available SOFA Conventions: GeneralFIR, GeneralFIRE, GeneralString, GeneralTF, MultiSpeakerBRIR, SimpleFreeFieldHRIR, SimpleFreeFieldSOS, SimpleFreeFieldTF, SimpleHeadphoneIR, SingleRoomDRIR
SOFAdbPath (local HRTF database): /Users/acustica/Documents/MATLAB/toolboxes/AKtools/2_Tools/ThirdParty/HRTFs/SOFA
SOFAdbURL (internet repository): http://www.sofacoustics.org/data
SOFA API -> detected
createNew
PTB-INFO: Using modified PortAudio V19.6.0-devel, revision unknown
PsychPortAudio initialized. Will use CoreAudio for audio.
ARDUINO not found
outchl: 
     1

RECORDING IN PROGRESS...

Recording Length: 2 seconds       65536

PsychPortAudio initialized. Will use CoreAudio for audio.
PTB-INFO: New audio device 2 with handle 0 opened as PortAudio stream:
PTB-INFO: For 2 channels Playback: Audio subsystem is Core Audio, Audio device name is H and F Series Multi Track Usb Audio
PTB-INFO: For 1 channels Capture: Audio subsystem is Core Audio, Audio device name is H and F Series Multi Track Usb Audio
PTB-INFO: Real samplerate 48000.000000 Hz. Input latency 88.583333 msecs, Output latency 172.687500 msecs.
PTB-INFO: Using modified PortAudio V19.6.0-devel, revision unknown
PsychPortAudio initialized. Will use CoreAudio for audio.
PTB-INFO: New audio device 2 with handle 0 opened as PortAudio stream:
PTB-INFO: For 2 channels Playback: Audio subsystem is Core Audio, Audio device name is H and F Series Multi Track Usb Audio
PTB-INFO: For 1 channels Capture: Audio subsystem is Core Audio, Audio device name is H and F Series Multi Track Usb Audio
PTB-INFO: Real samplerate 48000.000000 Hz. Input latency 88.583333 msecs, Output latency 172.687500 msecs.
Recording completed! 

Can`t run binaural metrics on non-stereo data
Displaying average analysis metrics for all channels
Reference to non-existent field 'ILD'.

Error in displayFields (line 51)
    set(handles.param_ILD,'String',[num2str(handles.data(idx).ILD),' dB']);

Error in runAnalysis (line 38)
handles = displayFields(handles);

Error in ScanIR_v2>measurePosition (line 1306)
handles = runAnalysis(handles);

Error in ScanIR_v2>measureIR (line 338)
    handles = measurePosition(hObject, handles);

Error in ScanIR_v2>measureButton_Callback (line 398)
handles = measureIR(hObject,handles);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in ScanIR_v2 (line 51)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)ScanIR_v2('measureButton_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.

**Comment by afgenovese** [comment]
Seems that there is a bug related to mono measurements in MLS, will update the code within the end of the week

**Comment by JP-Lisn** [comment]
Was checking out your project today and also ran into this issue... initially though it was somehow due to my audio interface configuration but glad I checked the known issues. 

This tool looks excellent btw, great work :)

**Comment by JP-Lisn** [comment]
Appears that this issue is also affecting Golay test signals. If PR #2 adequately resolves the issue for MLS test signals I can make the appropriate changes to golayZap_selectch.m

**Comment by afgenovese** [comment]
You are correct, it seems that multichannel capture with MLS and Golay codes was affected - looking at the pull requests and patching a fix.

**Comment by afgenovese** [comment]
I just pushed version 2.1 which reworks the MLS and Golay features + allows for different I/O devices, please consider all new branches from this current version. I will see how to integrate the pull requests shortly
